#-------------------------------
# General Site Settings

title: Garrick Ng | Software Engineer
description: Garrick Ng is freelance software developer who specialize in developing and designing high qualilty web applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Garrick Ng Di Feng
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook:  https://www.facebook.com/profile.php?id=100000190004640 # Add your Facebook handle
twitter:   https://twitter.com/Garrick_Bee # Add your Facebook handle
instagram: https://www.instagram.com/garrick_bee/ # Add your Facebook handle
github: https://github.com/GarrickBee # Add your Facebook handle
linkedin: https://www.linkedin.com/in/garrickng724/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

#-------------------------------
# Archive List
archive:
  - year: 2020
    feature: false
    name: Open Source Survey System
    type: Loading...
    image: beero.png
    built:
      - Codeigniter
      - PHP
      - MySQL
      - Boostrap
      - Angular
    link:
      github: https://github.com/GarrickBee/Beero-Survey
  - year: 2020
    feature: true
    name: Crowdsourcing Platform for Mask and Sanitizer
    type: Private
    image: maskfinder.png
    built:
      - Codeigniter
      - PHP
      - MySQL
      - Boostrap
      - JQuery
      - Google Map Api
    link:
      web: https://maskfinder.com
  - year: 2019
    feature: false
    name: Mystery Travel Platform
    type: Freelance
    built:
      - Codeigniter
      - PHP
      - MySQL
      - Boostrap
      - JQuery
    link:
      web: https://flytor.my
  - year: 2019
    feature: false
    name: Beero Solution
    type: Private
    built:
      - Codeigniter
      - PHP
      - MySQL
      - Boostrap
      - JQuery
    link:
      web: https://beerosolutions.com
  - year: 2019
    feature: true
    name: SEO friendly Ecommerce Platform
    image: beero.png
    type: Freelance
    built:
      - Codeigniter
      - PHP
      - MySQL
      - Boostrap
      - JQuery
    link:
      web: https://payment.personalizedherbs.com
  - year: 2018
    feature: true
    name: Online Education Learning Platform for Tution Center
    image: stem.png
    type: Freelance
    built:
      - Codeigniter
      - PHP
      - MySQL
      - RequireJs
      - Boostrap
      - JQuery
    link:
      web: https://stem.my
  - year: 2018
    feature: false
    name: Aircon Servicing and Ecommerce Platform
    type: Freelance
    built:
      - PHP
      - MySQL
      - JQuery
      - Boostrap
    link:
      web: https://aircondbuddy.com.my

#-------------------------------
# Skill List
skill:
  - Codeigniter
  - PHP
  - MySQL
  - JQuery
  - Javascript
  - HTML
  - CSS
  - Angular

#-------------------------------
# Skill List
timeline:
  - company: Beero
    name: Freelance Developer
    url: https://beerosolutions.com/
    date: July 2018 - Present
    desc:
      - Freelance Developer at Beero Solutions.
      - Develop mainly customize web applications for Small and Medium-sized Enterprises (SME)
      - Experience in developing Content Management System (CMS), Logistic System, Membership, e-Commerce etc.
  - company: University of Malaya
    name: Research Engineer
    url: https://www.um.edu.my/
    date: Sept 2018 - 2019
    desc:
      - Conduct research on open source robotic field.
      - Collabrate with Aerospace Malaysia Innovation Centre (AMIC) combining Internet of Things and robotic system
      - Participate in Langkawi International Maritime and Aerospace Exhibition 2019 (LIMA). Presenting combination of Programmable Logic Controller (PLC) with Universal Robots (UR) with internet solutions (IOT).
  - company: University of Malaya
    name: Graduated
    url: https://www.um.edu.my/
    date: Sept 2014 - Sept 2018
    desc:
      - Gradudated First Class with Bachelor of Engineering (Hons) - Mechanical Engineering
#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
